version: "3.9"

services:
  backup:
    build: ./backup
    env_file:
      - .env
    volumes:
      - ./${LOGS_DIR}:/data

  nginx:
    image: nginx:latest
    volumes:
      - ./${LOGS_DIR}:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"