name: Daily Backup

on:
  schedule:
    - cron: '0 20 * * *' # каждый день в 23:00 по Кишинёву (20:00 UTC)
  workflow_dispatch:     # вручную запускать тоже можно

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Клонировать репозиторий
      uses: actions/checkout@v3

    - name: 🐳 Запустить Docker Compose
      run: |
        docker-compose up --build --abort-on-container-exit

    - name: 📤 Загрузить логи как артефакт
      uses: actions/upload-artifact@v3
      with:
        name: backup-logs
        path: logs/